image: node:14

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm test

deploy:
  stage: deploy
  image: docker:stable
  only:
    - master
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - docker build -f docker/DockerFile -t $CI_REGISTRY_IMAGE/swap-backend:latest .
    - docker push $CI_REGISTRY_IMAGE/swap-backend
